name: LiveAnnounce
version: 1.2.0
main: org.ccoding.liveannounce.LiveAnnounce
api-version: "1.16"
author: ccoding
description: "Plugin para anunciar directos en el servidor"
softdepend:
  - PlaceholderAPI

commands:
  directo:
    description: "Anuncia tu directo a todo el servidor"
    usage: "/directo <plataforma> <canal>"
    aliases: [live, stream, livestream]
    permission: liveannounce.directo

  liveannounce:
    description: "Comandos principales del plugin"
    usage: "/liveannounce [help|version]"
    aliases: [la]

permissions:
  liveannounce.directo:
    description: "Permite usar el comando /directo para anunciar streams"
    default: op

  liveannounce.directo.bypass.cooldown:
    description: "Permite omitir el tiempo de espera (cooldown) del comando /directo"
    default: op

  liveannounce.admin:
    description: "Acceso total a todos los comandos de administración del plugin"
    default: op
    children:
      liveannounce.directo: true
      liveannounce.directo.bypass.cooldown: true
      liveannounce.admin.gui: true
      liveannounce.admin.history: true

  liveannounce.admin.gui:
    description: "Permite abrir la interfaz administrativa /la admin"
    default: op

  liveannounce.admin.history:
    description: "Permite ver el historial de anuncios"
    default: op
